apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: $GITOPS_SCM_PATH
    repoURL: $GITOPS_SCM_REPO
    targetRevision: HEAD
  syncPolicy:
    automated: {}
