apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: secondary-net-80-3f-5d-f9-e1-b2
spec:
  nodeSelector:
    kubernetes.io/hostname: 80-3f-5d-f9-e1-b2
  desiredState:
    interfaces:
      - name: br1
        type: linux-bridge
        state: up
        bridge:
          port:
            - name: br-port
              mac-address: 80:3F:5D:F9:D7:0C
      - name: br-port
        type: ethernet
        state: up
        mac-address: 80:3F:5D:F9:D7:0C
