

kind: ConfigMap
apiVersion: v1
metadata:
  name: my-rhdh-app-config
  namespace: rhdh-operator
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
data:
  app-config.yaml: |
    app:
      title: Services Australia Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
    backend:
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
      cors:
        origin: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${AUTH_GITHUB_APP_ID}
              clientId: ${AUTH_GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              webhookUrl: ${GITHUB_WEBHOOK_URL}
              webhookSecret: ${GITHUB_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_PRIVATE_KEY_FILE}
    catalog:
      processingInterval: { minutes: 1 }
      processing:
        cache:
          enabled: false # for development purposes, it is faster to disable the cache. Enable this for more stable environments as staging and production.
      lifecycles:
        - development
        - production
        - staging
      rules:
        - allow: [Location, Component, API, Resource, System, Domain, Group, User, Template]
      locations:
        # a first location: a software template for a basic Quarkus project
        - type: url
          target: https://github.com/maarten-vandeperre/developer-hub-training-exercises/blob/main/software-templates/default-quarkus-application/template.yaml
          rules:
            - allow: [Template]
      providers:
        github:
          # the provider ID can be any camelCase string
          providerId:
            organization: ${GITHUB_ORGANIZATION} # the name of the GitHub organization
            catalogPath: '/catalog-info.yaml' # the path where your catalog info file will be placed within projects than need to be scanned
            filters:
              branch: 'master' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
          # This one is needed for the demo-import repository: default branch on GitHub is 'main' now
          mainBranchProvider: # to enable scanning on the main branch
            organization: ${GITHUB_ORGANIZATION} # the name of the GitHub organization
            catalogPath: '/catalog-info.yaml' # the path where your catalog info file will be placed within projects than need to be scanned
            filters:
              branch: 'main' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
        ####### start - added to enable github authentication
        githubOrg:
          # the provider ID can be any camelCase string
          id: github-org
          orgs:
            - ${GITHUB_ORGANIZATION}
          githubUrl: https://github.com # 'https://' is required!
          schedule: # optional; same options as in TaskScheduleDefinition
            # supports cron, ISO duration, "human duration" as used in code
            frequency: { minutes: 1 }
            # supports ISO duration, "human duration" as used in code
            timeout: { minutes: 1 }
            initialDelay: { seconds: 15 }
        ####### end - added to enable github authentication
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true
