kind: ConfigMap
apiVersion: v1
metadata:
  name: my-rhdh-app-config
  namespace: rhdh-operator
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
data:
  app-config.yaml: |
    app:
      branding:
        theme:
          light:
            variant: "rhdh"
            mode: "light"
            palette:
              background:
                default: "#F8F8F8"
                paper: "#FFFFFF"
              banner:
                closeButtonColor: "#FFFFFF"
                error: "#E22134"
                info: "#2E77D0"
                link: "#000000"
                text: "#FFFFFF"
                warning: "#FF9800"
              border: "#E6E6E6"
              bursts:
                backgroundColor:
                  default: "#7C3699"
                fontColor: "#FEFEFE"
                gradient:
                  linear: "linear-gradient(-137deg, #4BB8A5 0%, #187656 100%)"
                slackChannelText: "#ddd"
              errorBackground: "#FFEBEE"
              errorText: "#CA001B"
              gold: "#FFD600"
              highlight: "#FFFBCC"
              infoBackground: "#ebf5ff"
              infoText: "#004e8a"
              link: "#0A6EBE"
              linkHover: "#2196F3"
              mode: "light"
              navigation:
                background: "#222427"
                indicator: "#0066CC"
                color: "#ffffff"
                selectedColor: "#ffffff"
                navItem:
                  hoverBackground: "#3c3f42"
                submenu:
                  background: "#222427"
              pinSidebarButton:
                background: "#BDBDBD"
                icon: "#181818"
              primary:
                main: "#0066CC"
              secondary:
                main: "#8476D1"
              status:
                aborted: "#757575"
                error: "#E22134"
                ok: "#1DB954"
                pending: "#FFED51"
                running: "#1F5493"
                warning: "#FF9800"
              tabbar:
                indicator: "#9BF0E1"
              textContrast: "#000000"
              textSubtle: "#6E6E6E"
              textVerySubtle: "#DDD"
              warningBackground: "#F59B23"
              warningText: "#000000"
              text:
                primary: "#151515"
                secondary: "#757575"
              rhdh:
                general:
                  disabledBackground: "#D2D2D2"
                  disabled: "#6A6E73"
                  searchBarBorderColor: "#E4E4E4"
                  formControlBackgroundColor: "#FFF"
                  mainSectionBackgroundColor: "#FFF"
                  headerBottomBorderColor: "#C7C7C7"
                  cardBackgroundColor: "#FFF"
                  sideBarBackgroundColor: "#212427"
                  cardBorderColor: "#C7C7C7"
                  tableTitleColor: "#181818"
                  tableSubtitleColor: "#616161"
                  tableColumnTitleColor: "#151515"
                  tableRowHover: "#F5F5F5"
                  tableBorderColor: "#E0E0E0"
                  tableBackgroundColor: "#FFF"
                  tabsBottomBorderColor: "#D2D2D2"
                  contrastText: "#FFF"
                primary:
                  main: "#0066CC"
                  focusVisibleBorder: "#0066CC"
                secondary:
                  main: "#8476D1"
                  focusVisibleBorder: "#8476D1"
                cards:
                  headerTextColor: "#151515"
                  headerBackgroundColor: "#FFF"
                  headerBackgroundImage: "none"

          dark:
            variant: "rhdh"
            mode: "dark"
            palette:
              background:
                default: "#333333"
                paper: "#424242"
              banner:
                closeButtonColor: "#FFFFFF"
                error: "#E22134"
                info: "#2E77D0"
                link: "#000000"
                text: "#FFFFFF"
                warning: "#FF9800"
              border: "#E6E6E6"
              bursts:
                backgroundColor:
                  default: "#7C3699"
                fontColor: "#FEFEFE"
                gradient:
                  linear: "linear-gradient(-137deg, #4BB8A5 0%, #187656 100%)"
                slackChannelText: "#ddd"
              errorBackground: "#FFEBEE"
              errorText: "#CA001B"
              gold: "#FFD600"
              highlight: "#FFFBCC"
              infoBackground: "#ebf5ff"
              infoText: "#004e8a"
              link: "#9CC9FF"
              linkHover: "#82BAFD"
              mode: "dark"
              navigation:
                background: "#0f1214"
                indicator: "#0066CC"
                color: "#ffffff"
                selectedColor: "#ffffff"
                navItem:
                  hoverBackground: "#3c3f42"
                submenu:
                  background: "#0f1214"
              pinSidebarButton:
                background: "#BDBDBD"
                icon: "#404040"
              primary:
                main: "#1FA7F8"
              secondary:
                main: "#B2A3FF"
              status:
                aborted: "#9E9E9E"
                error: "#F84C55"
                ok: "#71CF88"
                pending: "#FEF071"
                running: "#3488E3"
                warning: "#FFB84D"
              tabbar:
                indicator: "#9BF0E1"
              textContrast: "#FFFFFF"
              textSubtle: "#CCCCCC"
              textVerySubtle: "#727272"
              warningBackground: "#F59B23"
              warningText: "#000000"
    
              rhdh:
                general:
                  disabledBackground: "#444548"
                  disabled: "#AAABAC"
                  searchBarBorderColor: "#57585a"
                  formControlBackgroundColor: "#36373A"
                  mainSectionBackgroundColor: "#0f1214"
                  headerBottomBorderColor: "#A3A3A3"
                  cardBackgroundColor: "#292929"
                  sideBarBackgroundColor: "#1b1d21"
                  cardBorderColor: "#A3A3A3"
                  tableTitleColor: "#E0E0E0"
                  tableSubtitleColor: "#E0E0E0"
                  tableColumnTitleColor: "#E0E0E0"
                  tableRowHover: "#0f1214"
                  tableBorderColor: "#515151"
                  tableBackgroundColor: "#1b1d21"
                  tabsBottomBorderColor: "#444548"
                  contrastText: "#FFF"
                primary:
                  main: "#1FA7F8"
                  focusVisibleBorder: "#ADD6FF"
                secondary:
                  main: "#B2A3FF"
                  focusVisibleBorder: "#D0C7FF"
                cards:
                  headerTextColor: "#FFF"
                  headerBackgroundColor: "#0f1214"
                  headerBackgroundImage: "none"
        iconLogo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANcAAADrCAMAAADNG/NRAAAAilBMVEX///8AAAAFBQX8/Pzq6ur5+fnX19cICAj29vYLCwtoaGjz8/Pv7+/s7OwhISEQEBAYGBiurq67u7vCwsIoKCgcHBzg4OC0tLSqqqqQkJA1NTVMTExERES8vLwuLi4lJSWRkZE9PT1YWFhgYGDR0dF6enqioqJsbGxQUFCHh4djY2N0dHSamprKysoxs1DWAAAL/UlEQVR4nO1dDVfiOhBNmpa2FkT5BlGEVVfd9f//vTd3UlxBSgfoR3wnd8/Zs+uGbi+TTO5MJolSHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/bxhCFCnTHQ7vPzL6O34UmYLGSZQlkVJJZzj8mCjbNGn0fcVIDL3o0/Or1jrezENFf01UwbuaTEWJyl5+raj14s9UoWlS8CW0C/rGVfamgRi/zch2quhN0Vh9LPQWy1B1Cxu3DHqtv1oHBHrRQKdzQ7yK+iEZ7IObBfYDr12FfukkzAveUgcxXjTVep6owleN1NM/a6H9Kiv6DtqGCVNiQ7y2rxuTxfCu5js7+vEfNte2daBfw6i437aKuf7HyeKRKJHrO2SJbLdlrOMFGkaRe72xr4N09231W8KD7ACvl92G6IrLkFx90czQHnp7nPCu/TlZ5uAoe2YqX9DX+g60nOM12e+GKTuPTB3k9XuXV5rC1g+9ogmvRXT1t/EVxDp9O+wMrvZbBjFZ7DV0z3WE32hZzCOMGbOjJsw+L0su1euQZYpL5A7zojH2GCmIv6+9sYAXEXsFscglSVVkL3L3kdpziod5ccddZOawp2kLh3nFASboxIh4pTE1v+tBE7uDon4Yx+Tuo10TFPRDopUGep1FLg2wwn5InUvDYmiUv2+BvQL+FuA8iiVz4ygeX+hhczIYqaT8bYvGFzfV8ZIkFfkaN0bZUV4kqSDYTd4dj/HCfD0KSaY44hSP8YKkekNQnJvgGC+yGKn7no2/HcAxXiypHjMj4RWzpBplrkiq4/0Q/v7t09kf7YdWUt1NHHGKJeML/za3XQve41g/5DSCXvaomQM2K+HFmGecTyvlxZJqHSLQbN17SHgFc7Q05bwwn+u7LMra74ylvDA/I4KGDC7lFZP70AsXJFU5r4CY3bwZwfiikIUl1Z0DkkrUD8lkj4nth+VfAtw9nEe71CS8AJt+u9rPbxxsShbjeKzNwEXKixOmyG+UN0SalXMeSYsqWMgLZqKw5UrWGmMsVEcSx87wSpEDnZO97PLE8e8gJfGhl5nKWhxh4n4ISfW8FvVDK6kWrUoq+fhCV3zmP5RPDbCufu22KKnkvIDO7YpXiQTfAoXQ4y6Jr5Yk1Ym81Cw3SDkx+nXXhaRynleqO5G6vUFSXsAL8dgqaUtSnWavJ1IRs1hkL0gqjQnafXtRP0TGaSb6CCQVGXbda8crnjq+IPtmY1hM5j2wPha1MEWfzAuLmbe8VCkghlhgyZKq6ZW/c+yVqNsxaSWRUyR3vwgLVgld40Wu4Fb4MZZUry1kFc/gxWmcl7FQUgX9QI+bdx7n2Asmi7YWK5dUAcohjGm2K57Oi0HkZjfbMp0y0IR3nTVcDnEmLyQwbvtSrcjlECQUG3SKZ/Iin5ipWy2UVGi2Jp/oPi+70sVdsfxTVlItwiaXJM61Fy/RJjPRp9graizVOm+vnBwmaEgqwTPIZA8NlkNcxCtSEUsqiVtE3HIX4iONjLIL7ZUgHpN5e4jgVbepcojLeEF7kLsvz1HpbTlE2FCgeSEvllSpTFJx7v6h20wd5oX9kB3+7VgqqZBXnDRSDnERry29mdYin8hL1muWVHXPZZfzYkl1fYKkemiiHKICe50iqWyFabf+8pUKeHHGidy95EG2HOKmW3seuBpeFFyJJVUz5RBV+A0mp6apzjdNlHEj77EIeVKvj1xVvCCpxnaHR+lTIKmWSJjWmLuvzl4RnIfIKXI5xLpbazlEZbyg1Mnd7+8xOIgU5RDrWiVVZbywwU2a4ibd0ceKZo3lEFXx4m1j+QRdTsyWQ1zXWGFaGa+c3EzbQLMcFEQve8ZWszvOCyU57BVluXuNhGlNkqpae0WQVH3dlya56yuHqLofQlKVLqwzbDnEoktfhfu8IKkM0m8CXlZSreuRVNXyUjZ3P9X2qYJyiJSXaquXwZXz4o1j8nKIIKZ4LKq+HKIWXlZSSYjxysWyhnKIGnhxoDm9FpdDBIjHqpZUNfDilS4zk9nLbmVchlVv0azDXsbmPG4kT8zLIUZhxU6xDl703Se8P7/cYGgRYFVi8yPshbAlfJCsRnAcGuublx8wvmAuMxmLVCLqGgM9mv0Af8gCfbLW3zeyHwTITyuvBa6lHxrTgarvx+ULElAco6kyVWftq9e9kIiTO13+XA7TyFrpNP+ku7wUnxSDh5YjtRXp+npQh/Ct2l4QUTS2BCMrsMNvNXVfzxtsQzSdhawojDtif1B8/pFDvGjeYlqpqNgt1ddTFdWSq694fCWqs+S0p2BKhrO8J1a1VBdVxovFE3nCcflTgu2BRqNpDYwq5mV4hS9cSzZ6BHnUWY/LqJgX1lZ7WpbIxqYQPbqv8VycytZTsADZWaNAVPIgstbNtM6axOr8hsGhWbGWeEKIJ5q3MtWri1Y1vKx4Ik9Y7gdZPFE3vJ7m4ae7vAxO1VOIt8oR5+JJ37u/DpuLp7FMPPHwe6jPwVfGyxaZTJZaVk7EHXHwA+oceAlrglUEib0gM67v88oqp3mdJp443iLxVPe5iZfx4tNJyVqCFOineKJ4qwFcxguHqCpD8Vb5M+JcO13XKJ4q44WiVjNZCasA8B+Nhz+hXhRH5HYehGGktgq+mQ0dF9ZVRuqJVEaQCkQhdgek9YqnSngZnrnIWrGsvpfE02hQc1XU5byIUkb9ieKtUgSf4mnq/L4bZU/LCkXxFounAPFWczh3fwo2PRlZQi0XTzf1i6cKeMGpdcZi8US0hubQmcCO8cKU3FlzgCiYkrHTgRx87eLpIl4cRCKMXJS3t6aCJrxXzR54c4a9EkSSRpJQsydU0/NHzYiny3hxeddkIfKEthFZ6wfsX46wvqVPEU+DypeB6uD1KZ5EOfi+7jcmni7hhUi3s+IwUgBUhQ45teM4r8yOrVLkBQyIt5w/pyJgeymKtyQ5eGaGeKsVnGgviKfRCeIJLqOV07FOPQfGrkZKxZMeRi2dP3fq+HpaScUTtXqYqiRq59QvKa+Uq2c64UKwMW9bwMDrWy2d+SXjxReRUOcT7WdI7Qf0aNjiQWbi8w9TdoJ9eQFDPXUZ1fLCq8Z6E/2WuUI8k6bjlo6OOoEXe4FNtn9vRSEpLmBI6qmMr4oXF4xTZPirq0rPF7UfoA4bU3Tc5HEbp/NC+T4C3qteybnf+ot4GjWSg7+MF4zF1pKct5xHx626DCGvAOca/OKwq/RcYlv9+TBs/2IfAS9qsAltTqOUF59ZP2j6UKWzeFEn3CRwApJzpCGeBhTMNB1GnsQriO2I2fTspvKjvD4LGAYNrZiczYvXTOlN37eD5fi9FdYT3rQUb+3jaD+MsVRylWx1w/F7K1iJPLTvCS2O2gsXPLxnonsQ8iK1Ye0L/UIcs1cunqLtzs4SXqleDew+ZgdQYq8NburcFnSW3Fuhg0Fd1Z+no4BXqlk8ve98+UX3ZG2rPx1xGYyie5dYPL3vXid6mFccWFpjV1wGo8BeLJ6u9krAi/ohV3+uHBBPX1BgL1SRbDIhr88cvBtDi3GYF8bWrx6KW8vvoSPD9tEJm8/BH0NP74XALJ6oZ22S/WvoDvDaiqcGCxiE2L+XEy4Atcfv3UMvuXcPwraAIR061AMtvt03CvGUIt46lHTZywPkBQwPTRYwCLG/pQnWSvVVdmgzjFH7+SgWT/17Vy5p+4Ludy9A1voinnbwZ89eXP35UX/15xnY8xtI6/76Kp528LbLC6ntFUXHTRYwSLH56jF4xFx1C5oa1clbcbutynARRj1ti7KQTsMrXxVuTaWfr2zrPKEWY8XEPVMp8Oo+f3UCQYHLsIjMQOci13be/rDNnO5xTJafQwviSRXvC8SR+o88D8e8bmTL+x2ajP8BHJ5W1rcBv0MVFfOi4Mo8W6eJxZXgng/qcRJ8UPBjvsD/eqss1QLgcjP19G5Xza+fHaX0BZPhy9+/s6FEuJIO/Ji+/H0ZyPaet4rt4raRzEN2DjbKhdscS8COPVKiu+O4m9pr5pwnZmApeDuJb+NBZlq/QE8CvCCf8yd5V7YX9jk4KAo9PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PErwH6VWhjTWVzmfAAAAAElFTkSuQmCC
        fullLogo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANcAAADrCAMAAADNG/NRAAAAilBMVEX///8AAAAFBQX8/Pzq6ur5+fnX19cICAj29vYLCwtoaGjz8/Pv7+/s7OwhISEQEBAYGBiurq67u7vCwsIoKCgcHBzg4OC0tLSqqqqQkJA1NTVMTExERES8vLwuLi4lJSWRkZE9PT1YWFhgYGDR0dF6enqioqJsbGxQUFCHh4djY2N0dHSamprKysoxs1DWAAAL/UlEQVR4nO1dDVfiOhBNmpa2FkT5BlGEVVfd9f//vTd3UlxBSgfoR3wnd8/Zs+uGbi+TTO5MJolSHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/bxhCFCnTHQ7vPzL6O34UmYLGSZQlkVJJZzj8mCjbNGn0fcVIDL3o0/Or1jrezENFf01UwbuaTEWJyl5+raj14s9UoWlS8CW0C/rGVfamgRi/zch2quhN0Vh9LPQWy1B1Cxu3DHqtv1oHBHrRQKdzQ7yK+iEZ7IObBfYDr12FfukkzAveUgcxXjTVep6owleN1NM/a6H9Kiv6DtqGCVNiQ7y2rxuTxfCu5js7+vEfNte2daBfw6i437aKuf7HyeKRKJHrO2SJbLdlrOMFGkaRe72xr4N09231W8KD7ACvl92G6IrLkFx90czQHnp7nPCu/TlZ5uAoe2YqX9DX+g60nOM12e+GKTuPTB3k9XuXV5rC1g+9ogmvRXT1t/EVxDp9O+wMrvZbBjFZ7DV0z3WE32hZzCOMGbOjJsw+L0su1euQZYpL5A7zojH2GCmIv6+9sYAXEXsFscglSVVkL3L3kdpziod5ccddZOawp2kLh3nFASboxIh4pTE1v+tBE7uDon4Yx+Tuo10TFPRDopUGep1FLg2wwn5InUvDYmiUv2+BvQL+FuA8iiVz4ygeX+hhczIYqaT8bYvGFzfV8ZIkFfkaN0bZUV4kqSDYTd4dj/HCfD0KSaY44hSP8YKkekNQnJvgGC+yGKn7no2/HcAxXiypHjMj4RWzpBplrkiq4/0Q/v7t09kf7YdWUt1NHHGKJeML/za3XQve41g/5DSCXvaomQM2K+HFmGecTyvlxZJqHSLQbN17SHgFc7Q05bwwn+u7LMra74ylvDA/I4KGDC7lFZP70AsXJFU5r4CY3bwZwfiikIUl1Z0DkkrUD8lkj4nth+VfAtw9nEe71CS8AJt+u9rPbxxsShbjeKzNwEXKixOmyG+UN0SalXMeSYsqWMgLZqKw5UrWGmMsVEcSx87wSpEDnZO97PLE8e8gJfGhl5nKWhxh4n4ISfW8FvVDK6kWrUoq+fhCV3zmP5RPDbCufu22KKnkvIDO7YpXiQTfAoXQ4y6Jr5Yk1Ym81Cw3SDkx+nXXhaRynleqO5G6vUFSXsAL8dgqaUtSnWavJ1IRs1hkL0gqjQnafXtRP0TGaSb6CCQVGXbda8crnjq+IPtmY1hM5j2wPha1MEWfzAuLmbe8VCkghlhgyZKq6ZW/c+yVqNsxaSWRUyR3vwgLVgld40Wu4Fb4MZZUry1kFc/gxWmcl7FQUgX9QI+bdx7n2Asmi7YWK5dUAcohjGm2K57Oi0HkZjfbMp0y0IR3nTVcDnEmLyQwbvtSrcjlECQUG3SKZ/Iin5ipWy2UVGi2Jp/oPi+70sVdsfxTVlItwiaXJM61Fy/RJjPRp9graizVOm+vnBwmaEgqwTPIZA8NlkNcxCtSEUsqiVtE3HIX4iONjLIL7ZUgHpN5e4jgVbepcojLeEF7kLsvz1HpbTlE2FCgeSEvllSpTFJx7v6h20wd5oX9kB3+7VgqqZBXnDRSDnERry29mdYin8hL1muWVHXPZZfzYkl1fYKkemiiHKICe50iqWyFabf+8pUKeHHGidy95EG2HOKmW3seuBpeFFyJJVUz5RBV+A0mp6apzjdNlHEj77EIeVKvj1xVvCCpxnaHR+lTIKmWSJjWmLuvzl4RnIfIKXI5xLpbazlEZbyg1Mnd7+8xOIgU5RDrWiVVZbywwU2a4ibd0ceKZo3lEFXx4m1j+QRdTsyWQ1zXWGFaGa+c3EzbQLMcFEQve8ZWszvOCyU57BVluXuNhGlNkqpae0WQVH3dlya56yuHqLofQlKVLqwzbDnEoktfhfu8IKkM0m8CXlZSreuRVNXyUjZ3P9X2qYJyiJSXaquXwZXz4o1j8nKIIKZ4LKq+HKIWXlZSSYjxysWyhnKIGnhxoDm9FpdDBIjHqpZUNfDilS4zk9nLbmVchlVv0azDXsbmPG4kT8zLIUZhxU6xDl703Se8P7/cYGgRYFVi8yPshbAlfJCsRnAcGuublx8wvmAuMxmLVCLqGgM9mv0Af8gCfbLW3zeyHwTITyuvBa6lHxrTgarvx+ULElAco6kyVWftq9e9kIiTO13+XA7TyFrpNP+ku7wUnxSDh5YjtRXp+npQh/Ct2l4QUTS2BCMrsMNvNXVfzxtsQzSdhawojDtif1B8/pFDvGjeYlqpqNgt1ddTFdWSq694fCWqs+S0p2BKhrO8J1a1VBdVxovFE3nCcflTgu2BRqNpDYwq5mV4hS9cSzZ6BHnUWY/LqJgX1lZ7WpbIxqYQPbqv8VycytZTsADZWaNAVPIgstbNtM6axOr8hsGhWbGWeEKIJ5q3MtWri1Y1vKx4Ik9Y7gdZPFE3vJ7m4ae7vAxO1VOIt8oR5+JJ37u/DpuLp7FMPPHwe6jPwVfGyxaZTJZaVk7EHXHwA+oceAlrglUEib0gM67v88oqp3mdJp443iLxVPe5iZfx4tNJyVqCFOineKJ4qwFcxguHqCpD8Vb5M+JcO13XKJ4q44WiVjNZCasA8B+Nhz+hXhRH5HYehGGktgq+mQ0dF9ZVRuqJVEaQCkQhdgek9YqnSngZnrnIWrGsvpfE02hQc1XU5byIUkb9ieKtUgSf4mnq/L4bZU/LCkXxFounAPFWczh3fwo2PRlZQi0XTzf1i6cKeMGpdcZi8US0hubQmcCO8cKU3FlzgCiYkrHTgRx87eLpIl4cRCKMXJS3t6aCJrxXzR54c4a9EkSSRpJQsydU0/NHzYiny3hxeddkIfKEthFZ6wfsX46wvqVPEU+DypeB6uD1KZ5EOfi+7jcmni7hhUi3s+IwUgBUhQ45teM4r8yOrVLkBQyIt5w/pyJgeymKtyQ5eGaGeKsVnGgviKfRCeIJLqOV07FOPQfGrkZKxZMeRi2dP3fq+HpaScUTtXqYqiRq59QvKa+Uq2c64UKwMW9bwMDrWy2d+SXjxReRUOcT7WdI7Qf0aNjiQWbi8w9TdoJ9eQFDPXUZ1fLCq8Z6E/2WuUI8k6bjlo6OOoEXe4FNtn9vRSEpLmBI6qmMr4oXF4xTZPirq0rPF7UfoA4bU3Tc5HEbp/NC+T4C3qteybnf+ot4GjWSg7+MF4zF1pKct5xHx626DCGvAOca/OKwq/RcYlv9+TBs/2IfAS9qsAltTqOUF59ZP2j6UKWzeFEn3CRwApJzpCGeBhTMNB1GnsQriO2I2fTspvKjvD4LGAYNrZiczYvXTOlN37eD5fi9FdYT3rQUb+3jaD+MsVRylWx1w/F7K1iJPLTvCS2O2gsXPLxnonsQ8iK1Ye0L/UIcs1cunqLtzs4SXqleDew+ZgdQYq8NburcFnSW3Fuhg0Fd1Z+no4BXqlk8ve98+UX3ZG2rPx1xGYyie5dYPL3vXid6mFccWFpjV1wGo8BeLJ6u9krAi/ohV3+uHBBPX1BgL1SRbDIhr88cvBtDi3GYF8bWrx6KW8vvoSPD9tEJm8/BH0NP74XALJ6oZ22S/WvoDvDaiqcGCxiE2L+XEy4Atcfv3UMvuXcPwraAIR061AMtvt03CvGUIt46lHTZywPkBQwPTRYwCLG/pQnWSvVVdmgzjFH7+SgWT/17Vy5p+4Ludy9A1voinnbwZ89eXP35UX/15xnY8xtI6/76Kp528LbLC6ntFUXHTRYwSLH56jF4xFx1C5oa1clbcbutynARRj1ti7KQTsMrXxVuTaWfr2zrPKEWY8XEPVMp8Oo+f3UCQYHLsIjMQOci13be/rDNnO5xTJafQwviSRXvC8SR+o88D8e8bmTL+x2ajP8BHJ5W1rcBv0MVFfOi4Mo8W6eJxZXgng/qcRJ8UPBjvsD/eqss1QLgcjP19G5Xza+fHaX0BZPhy9+/s6FEuJIO/Ji+/H0ZyPaet4rt4raRzEN2DjbKhdscS8COPVKiu+O4m9pr5pwnZmApeDuJb+NBZlq/QE8CvCCf8yd5V7YX9jk4KAo9PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PErwH6VWhjTWVzmfAAAAAElFTkSuQmCC
      title: Services Australia Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
    backend:
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
      cors:
        origin: https://backstage-developer-hub-rhdh-operator.apps.hub.cszevaco.com/
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${AUTH_GITHUB_APP_ID}
              clientId: ${AUTH_GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              webhookUrl: ${GITHUB_WEBHOOK_URL}
              webhookSecret: ${GITHUB_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_PRIVATE_KEY_FILE}
    catalog:
      processingInterval: { minutes: 1 }
      processing:
        cache:
          enabled: false # for development purposes, it is faster to disable the cache. Enable this for more stable environments as staging and production.
      lifecycles:
        - development
        - production
        - staging
      rules:
        - allow: [Location, Component, API, Resource, System, Domain, Group, User, Template]
      locations:
        # a first location: a software template for a basic Quarkus project
        - type: url
          target: https://github.com/maarten-vandeperre/developer-hub-training-exercises/blob/main/software-templates/default-quarkus-application/template.yaml
          rules:
            - allow: [Template]
      providers:
        github:
          # the provider ID can be any camelCase string
          providerId:
            organization: ${GITHUB_ORGANIZATION} # the name of the GitHub organization
            catalogPath: '/catalog-info.yaml' # the path where your catalog info file will be placed within projects than need to be scanned
            filters:
              branch: 'master' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
          # This one is needed for the demo-import repository: default branch on GitHub is 'main' now
          mainBranchProvider: # to enable scanning on the main branch
            organization: ${GITHUB_ORGANIZATION} # the name of the GitHub organization
            catalogPath: '/catalog-info.yaml' # the path where your catalog info file will be placed within projects than need to be scanned
            filters:
              branch: 'main' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
        ####### start - added to enable github authentication
        githubOrg:
          # the provider ID can be any camelCase string
          id: github-org
          orgs:
            - ${GITHUB_ORGANIZATION}
          githubUrl: https://github.com # 'https://' is required!
          schedule: # optional; same options as in TaskScheduleDefinition
            # supports cron, ISO duration, "human duration" as used in code
            frequency: { minutes: 1 }
            # supports ISO duration, "human duration" as used in code
            timeout: { minutes: 1 }
            initialDelay: { seconds: 15 }
        ####### end - added to enable github authentication
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true
