kind: ConfigMap
apiVersion: v1
metadata:
  name: my-rhdh-app-config
  namespace: rhdh-operator
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
data:
  app-config.yaml: |
    app:
      title: RHDEVHUB
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true
    auth:
      providers: {}
