apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-oauth-devspaces-sandbox-secret
  namespace: external-secrets
spec:
  externalSecretName: "github-oauth-devspaces-sandbox-secret-external-secrets-generated"
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      github-oauth-devspaces-sandbox: yes-please
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: akeyless-cluster-secret-store

    refreshInterval: 1h
    target:
      name: github-oauth-devspaces-sandbox
      creationPolicy: Owner
      template:
        type: Opaque
        engineVersion: v2
        metadata:
          labels:
            app.kubernetes.io/part-of: che.eclipse.org
            app.kubernetes.io/component: oauth-scm-configuration
          annotations:
            che.eclipse.org/oauth-scm-server: github
            che.eclipse.org/scm-server-endpoint: https://github.com
            che.eclipse.org/scm-github-disable-subdomain-isolation: 'false'
        data:
          id: '{{ .id }}'
          secret: '{{ .secret }}'
    data:
      - secretKey: id
        remoteRef:
          key: /openshift-hub/github-oauth-devspaces-sandbox-id
      - secretKey: secret
        remoteRef:
          key: /openshift-hub/github-oauth-devspaces-sandbox-secret
