apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: sno
stringData:
  autoImportRetry: "5"
  # If you are using the kubeconfig file, add the following value for the kubeconfig file
  # that has the current context set to the cluster to import:
  # If you are using the token/server pair, add the following two values instead of
  # the kubeconfig file:
  token: {{.Values.spoke_token}}
  server: "https://api.{{.Values.spoke_clustername}}.{{.Values.spoke_clusterdomain}}:6443"
type: Opaque
