apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: primary-udn
  namespace: citrix-vdi-udn
spec:
  layer2:
    ipam:
      lifecycle: Persistent
    role: Primary
    subnets:
      - 192.168.254.0/24
  topology: Layer2
