apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightspeed-test-06
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: default
  project: hub
  source:
    path: cluster-go/lightspeed-benchmark/test-06
    repoURL: https://github.com/joelapatatechaude/ocluster/
    targetRevision: main
    helm:
