apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-import-sno
  namespace: openshift-gitops
  labels:
    type: infrastructure
    rhacm: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/rhacm-import
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
