apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odm
  namespace: openshift-gitops
  labels:
    type: demo
    app: odm
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/applications/odm
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
    - Prune=true

