apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-servicemesh
  namespace: openshift-gitops
  labels:
    type: applications
    service: ServiceMesh
    app: bookinfo
spec:
  destination:
    name: in-cluster
    namespace: bookinfo-servicemesh
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/applications/bookinfo-servicemesh
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - Prune=true
