apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multicloud-acm
  namespace: openshift-gitops
  labels:
    type: demo
    app: multicloud-acm
spec:
  destination:
    name: in-cluster
    namespace: multi-demo
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/applications/multicloud-acm-demo
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
