apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: citrix-vdi-app-of-apps
  namespace: openshift-gitops
  labels:
    app-of-apps: app-of-apps
    citrix-vdi: citrix-vdi
spec:
  destination:
    name: in-cluster
    namespace: default
  project: citrix-vdi
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: cluster-go/argo-app/citrix-vdi
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
    - Prune=true
