apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-console
  namespace: openshift-gitops
  labels:
    type: infrastructure
    service: ServiceMesh
spec:
  destination:
    name: in-cluster
    namespace: service-mesh-control-plane
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/ServiceMeshConsole
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
