apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch-serviceaccount
  namespace: openshift-gitops
  labels:
    type: infrastructure
    patch: core
    bootstrap: bootsrap
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/patch-serviceaccount
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    automated: {}
    syncOptions:
      - Prune=true
      - CreateNamespace=true
