apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    type: infrastructure
    rhdh: core
    devhub: core
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: hub
  source:
    path: cluster-go/infrastructure/devhub-sa
    repoURL: https://github.com/joelapatatechaude/ocluster/
    targetRevision: main
    helm:
      parameters:
        - name: "clustername"
          value: "$CLUSTER_NAME"
        - name: "clusterdomain"
          value: "$ROUTE53_DOMAIN"
  syncPolicy:
