apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-cpu
  namespace: openshift-gitops
  labels:
    type: infrastructure
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/vllm-cpu
    repoURL: https://github.com/joelapatatechaude/ocluster
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
