apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-gpu
  namespace: vllm-gpu-continue
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
