apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cpu-config
  namespace: vllm-cpu-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
