apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-oauth-sandbox-secret
  namespace: external-secrets
spec:
  externalSecretName: "github-oauth-sandbox-secret-generated"
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      github-oauth-sandbox: yes-please
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: akeyless-cluster-secret-store

    refreshInterval: 1h
    target:
      name: github-oauth-sandbox
      creationPolicy: Owner
    data:
      - secretKey: clientSecret
        remoteRef:
          key: /openshift-hub/github-oauth-sandbox-secret
