apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: openai-token-secret
  namespace: external-secrets
spec:
  externalSecretName: "openai-token-secret-generated"
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      openai-token: yes-please
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: akeyless-cluster-secret-store

    refreshInterval: 1h
    target:
      name: openai-api-keys
      creationPolicy: Owner
    data:
      - secretKey: apitoken
        remoteRef:
          key: /openshift-hub/openai-token
