apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: openai-api-keys
        models:
          - name: gpt-3.5-turbo
          - name: gpt-4o-mini
        name: myOpenai
        type: openai
        url: https://api.openai.com/v1

      - credentialsSecretRef:
          name: local-llm-api-keys
        models:
          - name: ibm-granite/granite-3.2-8b-instruct
        name: vllm-gpu
        type: openai
        url: http://vllm-gpu.vllm-gpu.svc.cluster.local/v1/

      - credentialsSecretRef:
          name: local-llm-api-keys
        models:
          - name: ibm-granite/granite-3.2-2b-instruct
        name: vllm-cpu
        type: openai
        url: http://vllm-cpu.vllm-cpu.svc.cluster.local/v1/

  ols:
    defaultModel: gpt-4o-mini
    defaultProvider: myOpenai
    logLevel: INFO
    userDataCollection:
      feedbackDisabled: false
      transcriptsDisabled: false
  olsDataCollector:
    logLevel: INFO
