apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - name: myOpenai
        type: openai
        credentialsSecretRef:
          name: openai-api-keys
        url: https://api.openai.com/v1
        models:
          - name: gpt-3.5-turbo
      - name: local-llm-3-2b
        credentialsSecretRef:
          name: local-llm-api-keys
        models:
          - name: models/granite-3.0-2b-instruct-Q4_K_M.gguf
        type: openai
        url: 'http://granite-3-2b.llm.svc.cluster.local:8080/v1/'
      - name: local-llm-3-8b
        credentialsSecretRef:
          name: local-llm-api-keys
        models:
          - name: models/granite-3.0-8b-instruct-Q4_K_M.gguf
        type: openai
        url: 'http://granite-3-8b.llm.svc.cluster.local:8080/v1/'
      - name: local-llm-deepsparse
        credentialsSecretRef:
          name: local-llm-api-keys
        models:
          - name: 
        type: openai
        url: 'http://deepsparse.llm.svc.cluster.local:8080/v1/'
  ols:
    defaultModel: /ModelDir/
    defaultProvider: local-llm-deepsparse
