apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: fix-image-lightspeed
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: v1
        kind: Pod
        namespace: openshift-lightspeed
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: lightspeed-service-api
      patchTemplate: |
        spec:
          containers:
            0:
              image: quay.io/rh_ee_cschmitz/openshift-lightspeed-patch:latest
      patchType: application/merge-patch+json
