apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: add-imagepullsecret-to-default-sa
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: default
        namespace: http-citrix-iso
      patchTemplate: |
        imagePullSecrets:
          - name: quay-schmitz-secret
      patchType: merge
