kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: pod-vm
  labels:
    app: postgres
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    app.openshift.io/runtime: postgresql
    app.openshift.io/runtime-namespace: pod-vm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
        deployment: postgres
    spec:
      volumes:
        - name: postgres-1
          emptyDir: {}
      containers:
        - name: postgres
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: the-password
          image: 'registry.redhat.io/rhel9/postgresql-16'
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: postgres-1
              mountPath: /var/lib/postgresql/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
