apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ratings
 namespace: bookinfo-compromised
spec:
 selector:
   matchLabels:
     app: ratings
     version: v1
 action: ALLOW
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/bookinfo-compromised/sa/bookinfo-reviews"]
   to:
   - operation:
       methods: ["GET"]
       paths: ["/ratings/*"]
 - to:
    - operation:
        methods: ["GET"]
        paths: ["/health"]
