kind: Secret
apiVersion: v1
metadata:
  name: my-rhdh-secrets
  namespace: rhdh-operator
stringData:
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: the-password-in-clear
  ARGOCD_URL: https://openshift-gitops-server-openshift-gitops.apps.andromeda.sandbox?????.opentlc.com
  K8S_SERVICE_ACCOUNT_TOKEN: "I NEED TO crate teh Service account, and get it's token"
  RHDH_GITHUB_APP_WEBHOOK_URL: "https://backstage-developer-hub-rhdh-operator.apps.andromeda.sandbox?????.opentlc.com"
  RHDH_GITHUB_APP_WEBHOOK_SECRET: "the-secret"
  RHDH_GITHUB_ORGANIZATION: "itil-sa"
  RHDH_GITHUB_APP_ID: "the-githubapp-id"
  RHDH_GITHUB_APP_CLIENT_ID: "the-githubapp-client-id"
  RHDH_GITHUB_APP_CLIENT_SECRET: "the client-secret"
  RHDH_GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    some keys

    NOTE THAT I STORED THE WHOLE THING READY TO WORK IN bitwarden Vault:
      summer-camp itil 2025

    -----END RSA PRIVATE KEY-----

type: Opaque
